RDKB-59864 : Fix webconfig build issue while running in local PC
Reason for change: To fix webconfig build failure due to "undefined reference to deleteForceSyncMsgQueue" on local container environment when webconfig bin is disabled.
Test Procedure: Webcfg build should be successful on both local pc and jenkins.
Risks: Low
Priority: P1
Signed-off-by: sadhyama_vengilat2@cable.comcast.com

(cherry picked from commit 7af8ec5d37544e8f6bad6dc2fa0c9d288e025b46)
Change-Id: Id9241c0289a9a43af667760ef9481674b43762dc