RDKDEV-740: Fix libav fetching failure
Reason for change:
Fixes:
  ERROR: lib32-libav-12.3-r0 do_fetch: Fetcher failure for URL:
    'https://libav.org/releases/libav-12.3.tar.xz'.
      Unable to fetch URL from any source.

 $ wget -d https://libav.org/releases/libav-12.3.tar.xz
 DEBUG output created by Wget 1.21.3 on linux-gnu.

 URI encoding = ‘UTF-8’
 Converted file name 'libav-12.3.tar.xz' (UTF-8) -> 'libav-12.3.tar.xz' (UTF-8)
 --2023-04-19 10:21:11--  https://libav.org/releases/libav-12.3.tar.xz
 Certificates loaded: 358
 Resolving libav.org (libav.org)... failed: Name or service not known.
 wget: unable to resolve host address ‘libav.org’

The host seems to be down so let's switch to GitHub.

Test Procedure: Sanity.
Risks: None.

Signed-off-by: Damian Wrobel <dwrobel.contractor@libertyglobal.com>

Change-Id: I51094fb56110b2fc3bf2cda645c28c444a015ce0